name: movie_catalog
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6

  #http:
  http: ^1.1.2
  #State Management
  get: 4.6.6
  #staggered_grid
  flutter_staggered_grid_view: ^0.7.0
  #Expandable Text
  expandable_text: ^2.3.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

